"""A clearly-labelled SYNTHETIC capture, for demos and as an end-to-end
smoke test of the analysis stack at realistic volume -- NOT market data and
never to be presented as such. The event name starts with "DEMO SYNTHETIC"
and every report/chart derived from it carries that name.

Injected ground truth (seconds after the shock): futures react at +1,
NIFTY spot at +3, BANKNIFTY spot at +4, the ATM options at +6 -- so a
correct pipeline must report spot leading its options by ~3s, the future
leading spot by ~2s, and NIFTY leading BANKNIFTY by ~1s.
"""
from __future__ import annotations

import random
from datetime import datetime, timedelta, timezone
from pathlib import Path

from diffusion_db import get_connection, insert_ticks
from event_calendar import ShockEvent

DEMO_EVENT = ShockEvent(
    event_name="DEMO SYNTHETIC RBI MPC",
    scheduled_timestamp_utc=datetime(2026, 10, 7, 4, 30, tzinfo=timezone.utc).isoformat(),
    timing_confidence="minute",
    market_hours_event=True,
    affected_underlyings=("NIFTY", "BANKNIFTY"),
    source_note="SYNTHETIC -- generated by synthetic.py, not market data",
)

INJECTED_LAGS = {"future_s": 1.0, "nifty_spot_s": 3.0, "banknifty_spot_s": 4.0, "option_s": 6.0}


def _series(rng, start, jump, jump_at_s, noise, tick_step, shock, pre_s, post_s, tick_grid=None, drift=0.0):
    out = []
    price = start
    n = int((pre_s + post_s) / tick_step)
    for i in range(n):
        offset = -pre_s + i * tick_step
        price += rng.gauss(drift, noise)
        level = price + (jump if offset >= jump_at_s else 0.0)
        if tick_grid:
            level = round(level / tick_grid) * tick_grid
        out.append((shock + timedelta(seconds=offset), level))
    return out


def build_demo_db(path: Path, pre_seconds: int = 600, post_seconds: int = 900, seed: int = 7) -> ShockEvent:
    rng = random.Random(seed)
    shock = datetime.fromisoformat(DEMO_EVENT.scheduled_timestamp_utc)
    conn = get_connection(path)
    name = DEMO_EVENT.event_name
    rows: list[dict] = []

    def add(key, kind, underlying, series, scale=100, strike=None, option_type=None, expiry=None, iv_series=None):
        for idx, (t, price) in enumerate(series):
            rows.append({
                "event_name": name, "instrument_key": key, "kind": kind, "underlying": underlying,
                "strike_paise": strike, "option_type": option_type, "timestamp_utc": t.isoformat(),
                "price_paise": int(round(price * scale)),
                "iv": None if iv_series is None else iv_series[idx][1],
                "expiry": expiry, "exchange_ts_ms": int((t.timestamp() - 0.3) * 1000),
            })

    common = dict(shock=shock, pre_s=pre_seconds, post_s=post_seconds)
    add("NSE_INDEX|Nifty 50", "spot", "NIFTY", _series(rng, 24000.0, 40.0, INJECTED_LAGS["nifty_spot_s"], 1.2, 1.0, **common, drift=0.002))
    add("NSE_INDEX|Nifty Bank", "spot", "BANKNIFTY", _series(rng, 55000.0, 90.0, INJECTED_LAGS["banknifty_spot_s"], 3.0, 1.0, **common))
    add("NSE_FO|NIFTYFUT", "future", "NIFTY", _series(rng, 24020.0, 40.0, INJECTED_LAGS["future_s"], 1.5, 0.5, **common, tick_grid=0.05), expiry="2026-10-27")
    add("NSE_FO|BANKFUT", "future", "BANKNIFTY", _series(rng, 55080.0, 90.0, INJECTED_LAGS["future_s"], 3.5, 0.5, **common, tick_grid=0.05), expiry="2026-10-27")

    for strike in (23900, 23950, 24000, 24050, 24100):
        moneyness = 24000 - strike
        for option_type, sign in (("CE", 1), ("PE", -1)):
            base = max(20.0, 150.0 + sign * moneyness * 0.5)
            iv_clock = _series(rng, 12.0, 2.0, INJECTED_LAGS["option_s"], 0.02, 0.5, **common)
            series = _series(rng, base, sign * 20.0, INJECTED_LAGS["option_s"], 0.25, 0.5, **common, tick_grid=0.05)
            add(f"NSE_FO|NIFTY{strike}{option_type}", "option", "NIFTY", series, strike=strike * 100,
                option_type=option_type, expiry="2026-10-13", iv_series=iv_clock)
    for option_type, sign in (("CE", 1), ("PE", -1)):
        series = _series(rng, 400.0, sign * 45.0, INJECTED_LAGS["option_s"], 0.6, 0.5, **common, tick_grid=0.05)
        add(f"NSE_FO|BANK55000{option_type}", "option", "BANKNIFTY", series, strike=5_500_000, option_type=option_type, expiry="2026-10-27")

    insert_ticks(conn, rows)
    conn.close()
    return DEMO_EVENT
